#!/bin/bash

SLEEP_TIME=5m   # Default time between checks.
SAFE_PERCENT=30  # Still safe at this level.
DANGER_PERCENT=15  # Warn when battery at this level.
CRITICAL_PERCENT=5  # Hibernate when battery at this level.

while [ true ]; do
    if [[ -n $(cat /sys/class/power_supply/BAT0/status | grep -i discharging) ]]; then
        rem_bat=$(cat /sys/class/power_supply/BAT0/capacity)

        if [[ $rem_bat -gt $SAFE_PERCENT ]]; then
        else
            SLEEP_TIME=1m
            if [[ $rem_bat -le $DANGER_PERCENT ]]; then
                notify-send "Batterie low" -u normal
            fi
            if [[ $rem_bat -le $CRITICAL_PERCENT ]]; then
                notify-send "Critical low batterie" -u critical
            fi
        fi
    fi

    sleep ${SLEEP_TIME}
done
